<?php 

// Define CONSTANTS used by this module: css class and title
define('EXPLORE_SECTION_CLASS', 'container opencollect collections');
define('EXPLORE_DIV_CLASS', 'col-sm-12 col-md-10 col-md-offset-1');
define('EXPLORE_DIV_TITLE', 'EXPLORE COLLECTIONS');
define('EXPLORE_LINK_TEXT', 'EXPLORE');

/**
 * Implements hook_menu().
 */
function explore_menu_menu() {
  $items['admin/config/user-interface/explore_menu'] = array(
    'title' => 'Shanti Explore Menu',
    'description' => 'Configure Shanti Collections Explore menu',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/structure/block/manage/explore_menu/explore_menu_block/configure'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function explore_menu_block_info() {
  $blocks = array();
  $blocks['explore_menu_block'] = array(
    'info' => t('Explore Collections Menu Block'),
   );
  return $blocks;
}

/**
* Implements hook_block_configure().
*   Configures classes for section and div element plus the title text for the popup
*/
function explore_menu_block_configure($delta='explore_menu_block') {
  $form = array();
  
  switch($delta) {
    case 'explore_menu_block' :
      // Explore Div Class Attribute Value
      $form['explore_section_class'] = array(
        '#type' => 'textfield',
        '#title' => t('Section Element Class'),
        '#description' => t('The value for the class attribute of the section element containing the content div'),
        '#default_value' => variable_get('explore_section_class', EXPLORE_SECTION_CLASS),
      );
      
      // Explore Div Class Attribute Value
      $form['explore_div_class'] = array(
        '#type' => 'textfield',
        '#title' => t('Containing Div Class'),
        '#description' => t('The value for the class attribute of the div containing the links to the collections'),
        '#default_value' => variable_get('explore_div_class', EXPLORE_DIV_CLASS),
      );
      
      // Explore Div Title
      $form['explore_div_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#description' => t('Title to display at the top of the collection links'),
        '#default_value' => variable_get('explore_div_title', EXPLORE_DIV_TITLE),
      );
            
      // Explore Div Link Text
      $form['explore_link_text'] = array(
        '#type' => 'textfield',
        '#title' => t('Link Text'),
        '#description' => t('Text for button in top bar'),
        '#default_value' => variable_get('explore_link_text', EXPLORE_LINK_TEXT),
      );
      
      // Explanation of where data comes from
      $form['data_explanation'] = array(
        '#type' => 'markup',
        '#markup' => '<div><strong>' . t('Note:') . '</strong> ' . 
          t('The links themselves are defined by a JSON file contained with the Shanti Explore Menu module\'s js folder.') . '</div>',
                      
      );

		  $form['update_links'] = array(
		    '#type' => 'button',
		    '#value' => t('Update Menu Links'),
		    '#attributes' => array('title' => t('Update Explore Menu Links from JSON File')),
		    '#prefix' => '<div class="form-item">',
		    '#suffix' => '<div id="em-update-msg"></div></div>',
		    '#ajax' => array(
				  'callback' => 'explore_menu_update',
		      'wrapper' => 'em-update-msg',
		      'method' => 'replace',
				),
		  );
	
      break; // Explore block case switch break
  }
  
  return $form;
}

/**
 * Used by theme to get the icon class for a link with a specific title. Means all links must have unique titles. Could use href?
 */
function explore_menu_get_iconclass($title) {
  $datastr = file_get_contents(drupal_get_path('module', 'explore_menu') . '/js/shanti-collections.json');
  $json = json_decode($datastr);
  foreach($json->links as $n => $link) {
    if($link->text == $title) {
      return $link->class;
    }
  }
  return FALSE;
}

/**
 * Updates explore menu links from JS at explore_menu/js/shanti-collections.json
 * TODO: Allow users to upload their custom js files (?)
 */
function explore_menu_update($filename = 'shanti-collections') {
	global $base_url, $base_path;
  $data = file_get_contents(drupal_get_path('module', 'explore_menu') . '/js/shanti-collections.json');
	// Remove all previous links
	$mn = 'shanti-explore-menu';
	$linktree = menu_tree_all_data($mn);
	$rct = 0;
	foreach($linktree as $lnm => $link) {
		$mlid = $link['link']['mlid'];
		menu_link_delete($mlid);
		$rct++;
	}
  $linkdata = json_decode($data);
	$msg = "";
	$ct = 0;
  foreach($linkdata->links as $n => $link) {
  	if(!isset($link->disabled) || $link->disabled == FALSE) {
  		$hrefchar = substr($link->href,0,1);
			if($hrefchar == '/' || $hrefchar == '#') {
				$link->href = $base_url . $base_path . $link->href;
			}
	    $item = array(
	      'link_path' => $link->href,
	      'link_title' => $link->text,
	      'menu_name' => $mn,
	      'weight' => ($n - 50),
	      'language' => $linkdata->language,
	      'plid' => 0, // Parent menu item, 0 if menu item is on top level
	      'module' => 'menu',
	    );
	    $mlid = menu_link_save($item); 
			if(!$mlid) {
				$msg .= "<li class=\"alert-warning\">{$item['link_title']} ({$item['link_path']}) could not be saved.</li>";
			} else {
				$ct++;
			}
		}
  }
  if(empty($msg)) {
  	$msg = "<ul><li class=\"alert-success\">Explore Collections Menus was successfully updated! ($rct items removed. $ct items added.)</li></ul>";
  } else {
  	$msg = '<ul>' . $msg . '</ul>';
  }
	return "<div id=\"em-update-msg\">$msg</div>";
}
